I# Exemplos com Tensor Flow#

Este notebook mostra exemplos de operações com tensores usando o TensorFlow

In [1]:
import tensorflow as tf
import numpy as np

#### 1. Quadrado da Diferença ####

In [2]:
x = [1,3,5,7,9,11]
y = 5

s = tf.math.squared_difference(x, y)
print(s.numpy())

[16  4  0  4 16 36]


#### 2. Encontrando a média ####

In [3]:
numbers = tf.constant([[4., 5.],[7., 3.]])

media = tf.reduce_mean(numbers)
print("Média geral = {}".format(media))

media = tf.reduce_mean(numbers, axis=0)
print("Média das colunas = {}".format(media))

media = tf.reduce_mean(numbers, axis=1)
print("Média das linhas = {}".format(media))

Média geral = 4.75
Média das colunas = [5.5 4. ]
Média das linhas = [4.5 5. ]


#### 3.  Geração de Números Aleatórios ####

*Distribuição Normal*

In [4]:
d_normal = tf.random.normal(shape=(3,2), mean=10, stddev=2)
print(d_normal.numpy())

[[ 9.066454   8.557968 ]
 [ 8.299252  10.991663 ]
 [10.5043955  9.061411 ]]


*Distribuição Uniforme*

In [12]:
d_unif = tf.random.uniform(shape=(2,4), minval=0, maxval=10, dtype=tf.int32, seed=None, name=None)
print(d_unif.numpy())

[[3 3 9 6]
 [1 2 0 6]]


*Encontrando índices do maior e do menor elemento em um tensor*

In [15]:
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5.numpy())

i = tf.argmax(t5)
print("Índice do maior elemento = {}".format(i))
print("Maior elemento = {}".format(t5[i].numpy()))

t6 = tf.reshape(t5, [3,3])
print(t6.numpy())

i = tf.argmax(t6, axis=0)
print("Índice do maior elemento nas linhas= {}".format(i))

i = tf.argmax(t6, axis=1)
print("Índice do maior elemento nas colunas= {}".format(i))

[  2  11   5  42   7  19  -6 -11  29]
Índice do maior elemento = 3
Maior elemento = 42
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]]
Índice do maior elemento nas linhas= [1 0 2]
Índice do maior elemento nas colunas= [1 0 2]


*Salvando e restaurando tensores usando checkpoints*

In [17]:
v  = tf.Variable([[1,3,5,7],[11,13,17,19]])
print(v.numpy())
checkpoint = tf.train.Checkpoint(var=v)
save_path = checkpoint.save('./vars')
v.assign([[0,0,0,0], [0,0,0,0]])
print(v.numpy())
checkpoint.restore(save_path=save_path)
print(v.numpy())


[[ 1  3  5  7]
 [11 13 17 19]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  3  5  7]
 [11 13 17 19]]
