In [22]:
import tensorflow as tf

Verificando a versão e outras características do TensorFlow


In [23]:
print('Versão:  {}'.format(tf.__version__))
print('Eager Execution:  {}'.format(tf.executing_eagerly()))
print('Versão do Keras:  {}'.format(tf.keras.__version__))

Versão:  2.1.0
Eager Execution:  True
Versão do Keras:  2.2.4-tf


Verificando se o TensorFlow está rodando numa CPU ou numa GPU

In [24]:
var = tf.Variable([3,3])

if tf.config.list_physical_devices('GPU'):
    print("Rodando na GPU")
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Rodando na CPU')

Rodando na CPU


Declaração de variáveis no TensorFlow

In [25]:
t0 = 24
t1 = tf.Variable(42)
t2 = tf.Variable([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])

t0, t1, t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

Declaração de Constantes

In [26]:
c1 = tf.constant(45)
c1
c1.numpy()

45

Tamanho de um tensor

In [27]:
print(t2.shape)

#Redimensionando um tesnor
r1 = tf.reshape(t2, [2,6])
print(r1.shape)
r2 = tf.reshape(t2, [1, 12])
print(r2)

(2, 2, 3)
(2, 6)
tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)


Dimensões(rank) de um tensor

In [28]:
print(tf.rank(t2))

tf.Tensor(3, shape=(), dtype=int32)


Cast de um tensor em uma variável Numpy/Python

In [29]:
print(t2.numpy())

print(t2[0,0,1].numpy())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2


Número de elementos de um tensor



In [30]:
n = tf.size(t2).numpy()
n

12

Operações elemento a elemento em um tensor

In [31]:
adicao = (t2 + t2).numpy()
print(adicao)

subtracao = (t2 - t2).numpy()
print(subtracao)

[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


Broadcasting

*No caso abaixo, o escalar é expandido
 em um tensor de igual tamanho e é realziada a 
 multiplicação elemento a elemento*

In [32]:
mult_escalar = (t2 * 4).numpy()
print(mult_escalar)

[[[ 4  8 12]
  [16 20 24]]

 [[28 32 36]
  [40 44 48]]]


Multiplicação de matrizes em TensorFlow

In [36]:
u = t2[0]
print(u.numpy())

v = t2[1]
print(v.numpy())

#Transpondo v para ajustar dimensionalidade da multiplicação
v = tf.transpose(v)
print(v.numpy())

mult_mat = tf.matmul(u, v).numpy()
print(mult_mat)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 7 10]
 [ 8 11]
 [ 9 12]]
[[ 50  68]
 [122 167]]


*Casting* tensores

In [37]:
casted = tf.cast(t2, tf.float32)
print(casted.numpy())

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


Tensores com dimensões irregulares(ragged tensors)

In [42]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])
print(ragged)
print(ragged[0, :])
print(ragged[1])


<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
